### ISSUE TITLE
Muscogee??

### ISSUE THREAD

**Issue by geobrando** [ingalls/parcel-cv#1]
Service from [current source](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/us/ga/muscogee.json) is no longer available, and actually looks to be the wrong county altogether.  Found a [qpublic webmap](http://qpublic7.qpublic.net/qpmap4/map.php?county=ga_muscogee&layers=parcels) that has parcels but did not see it in your list of available counties.

**Comment by geobrando** [comment]
Hey @ingalls Any plans to continue with this?

**Comment by ingalls** [comment]
Hey I can give that URL a try. Haven't run this script in a bit but web services like these usually are very slow to update so fingers crossed it will still work!
